### ISSUE TITLE
error al escanear

### ISSUE THREAD

**Issue by daimoxd** [GataNina-Li/GataBotV2#73]
me ha dado muchos error al escanear el codigo hasta instale linux para ver si termux era el problema y al parecer no el error es el siguiente
WARN [2022-05-15 18:57:34.608 +0000] (4368): error in QR gen
    class: "Baileys"
    error: {
      "name": "BaileysError",
      "status": 429,
      "context": {
        "query": [
          "admin",
          "Conn",
          "reref"
        ],
        "message": "Too Many Requests",
        "status": 429
      }
    }
WARN [2022-05-15 18:57:34.613 +0000] (4368): connect attempt 1 failed: Error: Unexpected status in 'admin': Too Many Requests(429), retrying...
    class: "Baileys"
    error: {}
INFO [2022-05-15 18:57:39.746 +0000] (4368): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
y se la pasa asi, alguna solucion?

**Comment by daimoxd** [comment]
tambien da este otro
TypeError: Cannot read properties of undefined (reading 'toString')
    at WAConnection.base64EncodedAuthInfo (/home/linoj/Escritorio/GataBotV2/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:126:42)
    at /home/linoj/Escritorio/GataBotV2/main.js:107:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) unhandledRejection
INFO [2022-05-15 18:55:09.398 +0000] (4368): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
(node:4368) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
INFO [2022-05-15 18:55:13.669 +0000] (4368): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"

**Comment by oddxnary** [comment]
Me pasa lo mismo.

**Comment by Deyner-Bot-MD** [comment]
X2
